fixed
next(iter(my_dict))

uppcase

reorg

TypeError: "reply_to" argument must be a list or tupl

use list instead so that nested lists arent created

check for instance instead

+ self.reply_to instead of [self.reply_to]

capitalizations

pad zeros